### ISSUE TITLE
UnboundLocalError: local variable 'bo' referenced before assignment

### ISSUE THREAD

**Issue by stijnh** [benvanwerkhoven/kernel_tuner#170]
Using `bayes_opt` with a low value for `max_fevals` or `time_limit` (for example, 10) results in the following exception:

```
Traceback (most recent call last):
  File "tune.py", line 91, in main
    tune_kernel(file, args)
  File "tune.py", line 48, in tune_kernel
    **options)
  File "../external/kernel_launcher/python/kernel_launcher/reader.py", line 312, in tune
    **options)
  File "/home/sheldens/miniconda3/lib/python3.7/site-packages/kernel_tuner/interface.py", line 553, in tune_kernel
    results, env = strategy.tune(runner, kernel_options, device_options, tuning_options)
  File "/home/sheldens/miniconda3/lib/python3.7/site-packages/kernel_tuner/strategies/bayes_opt.py", line 136, in tune
    return bo.results, runner.dev.get_environment()
UnboundLocalError: local variable 'bo' referenced before assignment
```

My suspicion is that the number of function evaluations is so low that Bayesian optimization is not able to initialize its model?

https://github.com/benvanwerkhoven/kernel_tuner/blob/e47872a07ee7df2e57ad77d12edf9decaa4ef335/kernel_tuner/strategies/bayes_opt.py#L129-L136

**Comment by stijnh** [comment]
See the following minimal example:

```python
import kernel_tuner

source = """
__global__ 
void foo() {

}
"""

problem_size = 100
args = []
tune_params = dict(
    block_size_x=[1, 2, 4, 8, 16, 32, 64],
    block_size_y=[1, 2, 4],
    block_size_z=[1, 2, 4],
)

kernel_tuner.tune_kernel(
        "foo",
        source,
        100,
        args,
        tune_params,
        strategy="bayes_opt",
        strategy_options=dict(
            max_fevals=5
        )
)
```

That results in the following exception:

```
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    max_fevals=5
  File "/home/sheldens/miniconda3/lib/python3.7/site-packages/kernel_tuner/interface.py", line 553, in tune_kernel
    results, env = strategy.tune(runner, kernel_options, device_options, tuning_options)
  File "/home/sheldens/miniconda3/lib/python3.7/site-packages/kernel_tuner/strategies/bayes_opt.py", line 136, in tune
    return bo.results, runner.dev.get_environment()
UnboundLocalError: local variable 'bo' referenced before assignment
```

I'm using the latest master branch: e47872a07ee7df2e57ad77d12edf9decaa4ef335
